In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Read the data
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Maze/Logistic Regression/weatherAlbury.csv")
print('Size of weather data frame is :',df.shape)
df.head()

Size of weather data frame is : (3011, 13)

,Date,Location,MinTemp,MaxTemp,Rainfall,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,01/12/2008,Albury,13.4,22.9,0.6,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,02/12/2008,Albury,7.4,25.1,0.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,03/12/2008,Albury,12.9,25.7,0.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,04/12/2008,Albury,9.2,28.0,0.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,05/12/2008,Albury,17.5,32.3,1.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No

In [ ]:
# Preprocess the data

df = df.dropna()
print("new shape:" ,df.shape)
df['RainToday'].replace({'No': 0, 'Yes': 1},inplace = True)
df['RainTomorrow'].replace({'No': 0, 'Yes': 1},inplace = True)

new shape: (2981, 13)

<ipython-input-3-f9f541358b31>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RainToday'].replace({'No': 0, 'Yes': 1},inplace = True)
<ipython-input-3-f9f541358b31>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RainTomorrow'].replace({'No': 0, 'Yes': 1},inplace = True)

In [ ]:
df.head(20)

,Date,Location,MinTemp,MaxTemp,Rainfall,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,01/12/2008,Albury,13.4,22.9,0.6,71.0,22.0,1007.7,1007.1,16.9,21.8,0,0
1,02/12/2008,Albury,7.4,25.1,0.0,44.0,25.0,1010.6,1007.8,17.2,24.3,0,0
2,03/12/2008,Albury,12.9,25.7,0.0,38.0,30.0,1007.6,1008.7,21.0,23.2,0,0
3,04/12/2008,Albury,9.2,28.0,0.0,45.0,16.0,1017.6,1012.8,18.1,26.5,0,0
4,05/12/2008,Albury,17.5,32.3,1.0,82.0,33.0,1010.8,1006.0,17.8,29.7,0,0
5,06/12/2008,Albury,14.6,29.7,0.2,55.0,23.0,1009.2,1005.4,20.6,28.9,0,0
6,07/12/2008,Albury,14.3,25.0,0.0,49.0,19.0,1009.6,1008.2,18.1,24.6,0,0
7,08/12/2008,Albury,7.7,26.7,0.0,48.0,19.0,1013.4,1010.1,16.3,25.5,0,0
8,09/12/2008,Albury,9.7,31.9,0.0,42.0,9.0,1008.9,1003.6,18.3,30.2,0,1
9,10/12/2008,Albury,13.1,30.1,1.4,58.0,27.0,1007.0,1005.7,20.1,28.2,1,0
10,11/12/2008,Albury,13.4,30.4,0.0,48.0,22.0,1011.8,1008.7,20.4,28.8,0,1
11,12/12/2008,Albury,15.9,21.7,2.2,89.0,91.0,1010.5,1004.2,15.9,17.0,1,1
12,13/12/2008,Albury,15.9,18.6,15.6,76.0,93.0,994.3,993.0,17.4,15.8,1,1
13,14/12/2008,Albury,12.6,21.0,3.6,65.0,43.0,1001.2,1001.8,15.8,19.8,1,0
15,17/12/2008,Albury,14.1,20.9,0.0,69.0,82.0,1012.2,1010.4,17.2,18.1,0,1
16,18/12/2008,Albury,13.5,22.9,16.8,80.0,65.0,1005.8,1002.2,18.0,21.5,1,1
17,19/12/2008,Albury,11.2,22.5,10.6,47.0,32.0,1009.4,1009.7,15.5,21.0,1,0
18,20/12/2008,Albury,9.8,25.6,0.0,45.0,26.0,1019.2,1017.1,15.8,23.2,0,0
19,21/12/2008,Albury,11.5,29.3,0.0,56.0,28.0,1019.3,1014.8,19.1,27.3,0,0
20,22/12/2008,Albury,17.1,33.0,0.0,38.0,28.0,1013.6,1008.1,24.5,31.6,0,0

In [ ]:
# Implement Logistic Regression Model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression


X = df[["MinTemp", "MaxTemp", "Rainfall", "Humidity9am", "Humidity3pm", "Pressure9am",
        "Pressure3pm", "Temp9am", "Temp3pm", "RainToday"]]
y = df.RainTomorrow

# random_state = number of shuffle
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20, random_state=42)

# Default max-iter = 100
logreg = LogisticRegression(max_iter = 200)
logreg.fit(X_train,y_train)

y_pred = logreg.predict(X_test)
# y_pred

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
# Evaluate the model

from sklearn.metrics import accuracy_score

score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)

Accuracy : 0.8676716917922948

The model get at least 86% of predictions correctly.

In [ ]:
# Making predictions
Obs = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Maze/Logistic Regression/weatherObs.xlsx")

Obs['RainToday'].replace({'No': 0, 'Yes': 1},inplace = True)
newData = Obs.values

y_pred = logreg.predict(newData)
print(y_pred)

[0 1 0]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(